// import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// // This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

// /**
//  * Creating a sidebar enables you to:
//  - create an ordered group of docs
//  - render a sidebar for each doc of that group
//  - provide next/previous navigation

//  The sidebars can be generated from the filesystem, or explicitly defined here.

//  Create as many sidebars as you want.
//  */
// const sidebars: SidebarsConfig = {
//   // By default, Docusaurus generates a sidebar from the docs folder structure
//   docs: [{type: 'autogenerated', dirName: '.'}],
//   // sidebars.js
// //   docs: [
// //     'index',
// //     'before_you_start',
// //     'use_cases',
// //     'architecture',
// //     'installation_upgrade',
// //     'quickstart',
// //     'image_catalog',
// //     'bootstrap',
// //     'database_import',
// //     'security',
// //     'instance_manager',
// //     'scheduling',
// //     'resource_management',
// //     'failure_modes',
// //     'rolling_update',
// //     'replication',
// //     'logical_replication',
// //     'backup',
// //     'wal_archiving',
// //     'recovery',
// //     'service_management',
// //     'postgresql_conf',
// //     'declarative_role_management',
// //     'declarative_database_management',
// //     'tablespaces',
// //     'operator_conf',
// //     'cluster_conf',
// //     'storage',
// //     'labels_annotations',
// //     'monitoring',
// //     'logging',
// //     'certificates',
// //     'ssl_connections',
// //     'applications',
// //     'connection_pooling',
// //     'replica_cluster',
// //     'kubernetes_upgrade',
// //     'postgres_upgrades',
// //     'kubectl-plugin',
// //     'failover',
// //     'troubleshooting',
// //     'fencing',
// //     'declarative_hibernation',
// //     'postgis',
// //     'e2e',
// //     'container_images',
// //     'imagevolume_extensions',
// //     'cnpg_i',
// //     'operator_capability_levels',
// //     'controller',
// //     'samples',
// //     'networking',
// //     'benchmarking',
// //     'faq',
// //     'cloudnative-pg.v1',
// //     'supported_releases',
// //     'preview_version',
// //     'release_notes',
// //     {
// //       type: 'category',
// //       label: 'CNCF Projects Integrations',
// //       items: [
// //         'cncf-projects/external-secrets',
// //         'cncf-projects/cilium',
// //       ],
// //     },
// //     {
// //       type: 'category',
// //       label: 'Appendixes',
// //       items: [
// //         'appendixes/backup_volumesnapshot',
// //         'appendixes/backup_barmanobjectstore',
// //         'appendixes/object_stores',
// //       ],
// //     },
// //   ],
// };


//   // But you can create a sidebar manually
//   /*
//   tutorialSidebar: [
//     'intro',
//     'hello',
//     {
//       type: 'category',
//       label: 'Tutorial',
//       items: ['tutorial-basics/create-a-document'],
//     },
//   ],
//    */


// export default sidebars;
import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const sidebars: SidebarsConfig = {
  docs: [
    'index',
    'before_you_start',
    'use_cases',
    'architecture',
    'installation_upgrade',
    'quickstart',
    'image_catalog',
    'bootstrap',
    'database_import',
    'security',
    'instance_manager',
    'scheduling',
    'resource_management',
    'failure_modes',
    'rolling_update',
    'replication',
    'logical_replication',
    'backup',
    'wal_archiving',
    'recovery',
    'service_management',
    'postgresql_conf',
    'declarative_role_management',
    'declarative_database_management',
    'tablespaces',
    'operator_conf',
    'cluster_conf',
    'storage',
    'labels_annotations',
    'monitoring',
    'logging',
    'certificates',
    'ssl_connections',
    'applications',
    'connection_pooling',
    'replica_cluster',
    'kubernetes_upgrade',
    'postgres_upgrades',
    'kubectl-plugin',
    'failover',
    'troubleshooting',
    'fencing',
    'declarative_hibernation',
    'postgis',
    'e2e',
    'container_images',
    'imagevolume_extensions',
    'cnpg_i',
    'operator_capability_levels',
    'controller',
    'samples',
    'networking',
    'benchmarking',
    'faq',
    'cloudnative-pg.v1',
    'supported_releases',
    'preview_version',
    'release_notes',
    {
      type: 'category',
      label: 'CNCF Projects Integrations',
      items: [
        'cncf-projects/external-secrets',
        'cncf-projects/cilium',
      ],
    },
    {
      type: 'category',
      label: 'Appendixes',
      items: [
        'appendixes/backup_volumesnapshot',
        'appendixes/backup_barmanobjectstore',
        'appendixes/object_stores',
      ],
    },
  ],
};

export default sidebars;
